[project]
name = "omc-mcp"
version = "0.1.0"
description = "An experimental MCP server for OpenMultipleChoice."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.1",
    "ruff>=0.11.11",
]
